#!/usr/bin/env bash
# script to install Nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /tmp/index.html

echo "http {
	server {
		listen 80;

		root /tmp;
		index index.html;
	}
}

events { }
" > /etc/nginx/nginx.conf
nginx -s reload
