#!/usr/bin/env bash
# script to install Nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "http {
	server {
		listen 80;
		location /redirect_me {
			return 301 http://www.google.com;
		}
	}
}

events { }
" > /etc/nginx/nginx.conf
service nginx start
