#!/usr/bin/env bash
# script to redirect

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "http {
	server {
		listen 80;
		location /redirect_me {
			rewrite ^ /redirected permanent;
		}
	}
}

events { }
" > /etc/nginx/sites-available/default
service nginx restart
