#!/usr/bin/env bash
# script to redirect to google.com

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

echo "http {
		server {
			listen 80 default_server;
			listen [::]:80 default_server;

			location /redirect_me {
				return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;;
			}
	}
}

events { }
" > /etc/nginx/nginx.conf
if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
