#!/usr/bin/env bash
# This script displays bad luck from China on the 4th iteration, bad luck from Japan on the 9th iteration and bad luck from Italy on the 17th iteration

counter=1

while [ $counter -le 20 ]
do
	echo $counter
	if [ $counter -eq 4 ]
	then
		echo "bad luck from China"
	elif [ $counter -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]
	then
		echo "bad luck from Italy"		
	fi
	((counter++))
done
